[project]
name = "qa-diplom-project"
version = "0.1.0"
description = "QA diploma project"
requires-python = ">=3.14"
dependencies = [
    "allure-pytest>=2.16.0",
    "faker>=40.23.0",
    "playwright>=1.60.0",
    "pydantic>=2.13.4",
    "pytest>=9.0.3",
    "pytest-playwright>=0.8.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "taskipy>=1.14.1",
]
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
addopts = "-v  --alluredir=allure-results --clean-alluredir"
base_url = "http://localhost:3000"
markers = [ 
    "home: Home page tests",
    "login: Login tests",
    "dashboard: Dashboard tests",
    "boards: Boards tests",
    "tasks: Tasks tests",
    "logout: Logout tests",
    "api: API tests",
    "ui: UI tests",
    ]
[tool.taskipy.tasks]
report = "allure serve allure-results"
clean = "rm -rf allure-results allure-report"

[dependency-groups]
dev = [
    "pylint>=4.0.6",
]
