[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v -ra
markers =
    user1: тест страницы задач
    user2: тест информации о пользователе
    user3: тест страницы досок
    user4: тест выхода из аккаунта